name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: set -eu

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.OCAT }}" > "$HOME/.ssh/key2"
      - run: chmod 600 "$HOME/.ssh/key2"

      - name: Rsync files to server
        run: |
          cd app
          export SSHPASS=${{ secrets.SSH_PASSWORD_OCAT }}
          rsync -e "sshpass -e ssh -p 3333 -i $HOME/.ssh/key2 -o StrictHostKeyChecking=no" --archive --compress --update . sattelites@185.237.225.43:/var/www/sattelites/data/www/bio.leonidov.dev                           

#      - name: Send success message to Telegram
#        if: success()
#        run: |
#          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
#                  -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
#                  -d text="🟢 $GITHUB_REPOSITORY [${{ github.event.pusher.name }}] - OK"
#      - name: Send error message to Telegram
#        if: failure()
#        run: |
#          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
#          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
#          -d text="🔴 $GITHUB_REPOSITORY [${{ github.event.pusher.name }}] - ERROR"